spring.application.name=database

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://ep-green-lake-an8b78qb-pooler.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:neondb_owner}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:npg_Cc7Wnl9DxgEo}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.app.jwtSecret= tranhuyduc2004ajkdhjaskhdaskjdhkjashdjahsjdhksahkdhsadhashdhajskhdkjakjdaskjhdjsah
spring.app.jwtExpirationMs = 30000000
